---
- name: add Docker repository
  yum_repository:
    name: docker
    description: Docker repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg

- name: install docker
  yum: name=docker-engine state=latest

- name: create docker certs dir
  file: path=/etc/docker/certs.d state=directory

- name: create private docker registry cert dir
  file: path=/etc/docker/certs.d/docker-registry.service.private:5000 state=directory

- name: trust private docker registry cert
  copy: src=docker-registry.crt dest=/etc/docker/certs.d/docker-registry.service.private:5000/ca.crt owner=root group=root

- name: start docker
  service: name=docker state=started
