---
- name: add Docker repository
  yum_repository:
    name: docker
    description: Docker repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg

- name: install docker
  yum: name=docker-engine state=latest

- name: start docker
  service: name=docker state=started
