---
- hosts: apigateway-servers
  tasks:
  - name: add Docker repository
    yum_repository:
      name: docker
      description: Docker repository
      baseurl: https://yum.dockerproject.org/repo/main/centos/7/
      gpgcheck: yes
      gpgkey: https://yum.dockerproject.org/gpg

  - name: install docker
    yum: name=docker-engine state=latest

  - name: start docker daemon
    service: name=docker state=started

  - name: create apigateway-db container
    docker_container:
      name: apigateway-db
      image: postgres
      env:
        POSTGRES_USER: kong
        POSTGRES_DB: kong

  - name: create apigateway container
    docker_container:
      name: apigateway
      image: kong
      env:
        KONG_DATABASE: postgres
        KONG_PG_HOST: apigateway-db
      links:
        - "apigateway-db:apigateway-db"
      ports:
        - "8000:8000"
        - "8001:8001"
