---
- hosts: cicd-servers
  tasks:
  - name: add Docker repository
    yum_repository:
      name: docker
      description: Docker repository
      baseurl: https://yum.dockerproject.org/repo/main/centos/7/
      gpgcheck: yes
      gpgkey: https://yum.dockerproject.org/gpg

  - name: install docker
    yum: name=docker-engine state=latest

  - name: start docker daemon
    service: name=docker state=started

  - name: create jenkins container
    docker_container:
      name: cicd
      image: jenkins
      published_ports: 8081:8080
